# 타입이 post-change인 repository_dispatch 이벤트를 blog 레포에 트리거하여,
# 블로그 코어의 배포 워크플로 실행
# https://docs.github.com/ko/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event

name: 블로그 코어에 변화 통지

on:
  push:
    branches: [main]

  # Actions 탭에서 수동으로 워크플로 실행 허용
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: 블로그 코어의 배포 워크플로 실행
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/yejunian/blog/dispatches \
            -d '{"event_type":"post-change"}'
